name: Run CI
on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint_and_test:
    name: Static code analyze & Unit test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: staging
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.2

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.7.8'

      - name: Set up staging environment
        env:
          ENV_STAGING: ${{ secrets.ENV_STAGING }}
        run: echo "$ENV_STAGING" > .env.staging

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run code generator
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Check for any formatting issues in the code
        run: dart format --set-exit-if-changed .

      - name: Statically analyze the Dart code for any errors
        run: flutter analyze .

      - name: Run widget tests, unit tests
        run: flutter test --machine --coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/lcov.info
          flags: unittests # optional
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: false
          verbose: true
